[toolchain]
channel = "nightly"
# channel = "nightly-2022-05-20"
# channel = "stable"
#channel = "1.81"

# https://rust-lang.github.io/rustup-components-history/
components = ["rustfmt", "clippy"]
targets = [
  "aarch64-unknown-none-softfloat"
]
